<?php


class Programmer extends Employee
{
    private $langs = [];

    /**
     * @return array
     */
    public function getLangs()
    {
        return $this->langs;
    }

    /**
     * @param array $langs
     */
    public function setLangs($langs)
    {
        $this->langs = $langs;
    }

        public function setName($name)
    {
        if (strlen($name)<=10) {
            return parent::setName($name); // TODO: Change the autogenerated stub
        }
    }
}