<?php


class Student extends User
{
    private $course;

    /**
     * @return mixed
     */
    public function getCourse()
    {
        return $this->course;
    }

    /**
     * @param mixed $course
     */
    public function setCourse($course)
    {
        $this->course = $course;
    }

    public function setName($name)
    {
        if (strlen($name<=10)){
        return parent::setName($name); // TODO: Change the autogenerated stub
    }
    }
}